data:
  root_dir: ./data/benchmark/cof
  matid_csv: benchmark
  override: false

  num_grids: [8, 8, 8]
  pes_num_grids: [8, 8, 8]
  repulsion_distance: 0.0

train:
  enable_pes: true
  enable_task: true

  task_name: highbar
  msg_routes: ['p2pv']
  readout_node: vn

  max_epochs: 60
  accumulate_grad_batches: 1
  precision: 16-mixed
  batch_size: 16
  model: schnet
  device: [3]
  ckpt_path: ~

  log_dir: ./lightning_logs/multitask/multitask/cof/schnet


# default optimizer
optimize:
  type: default
  lr: 0.001
  decay_power: "cosine"
  weight_decay: 0.01
  warmup_steps: 0.1
  max_steps: -1
  optim_type: "adamw"
  end_lr: 0
  lr_mult: 1