data:
  root_dir: ./data/benchmark/ch4n2
  matid_csv: benchmark
  override: true

  num_grids: [8, 8, 8]
  pes_num_grids: [8, 8, 8]
  repulsion_distance: 0.0

train:
  enable_pes: false
  enable_task: true

  task_name: ch4n2ratio-1bar
  msg_routes: ['p2p']
  readout_node: pn

  max_epochs: 30
  accumulate_grad_batches: 1
  precision: 16-mixed
  batch_size: 2
  model: jmp
  device: [2, 3, 4]
  ckpt_path: ~

  log_dir: ./lightning_logs/jmp/base/ch4n2/jmp


# default optimizer
optimize:
  type: jmp