data:
  root_dir: ./data/benchmark/zeolite
  matid_csv: benchmark
  override: false

  num_grids: [8, 8, 8]
  pes_num_grids: [8, 8, 8]
  repulsion_distance: 0.0

train:
  enable_pes: true
  enable_task: true

  task_name: heat_of_adsorption
  msg_routes: ['p2pv']
  readout_node: vn

  max_epochs: 30
  accumulate_grad_batches: 1
  precision: 16-mixed
  batch_size: 2
  model: jmp
  device: [2, 3, 4]
  ckpt_path: ~

  log_dir: ./lightning_logs/jmp/multitask/zeolite/jmp


# default optimizer
optimize:
  type: jmp