data:
  root_dir: ./data/test
  matid_csv: benchmark
  train_matid_csv: benchmark
  val_matid_csv: benchmark
  test_matid_csv: benchmark
  override: true

  num_grids: [8, 8, 8]
  pes_min_lat_len: 30
  pes_num_grids: [60, 60, 60]
  repulsion_distance: 0

train:
  enable_ff: false
  enable_task: true

  task_name: bandgap
  msg_routes: ['p2p']
  readout_node: pn

  max_epochs: 100
  accumulate_grad_batches: 1
  precision: 16-mixed
  batch_size: 16
  model: schnet
  device: [1]
  ckpt_path: ~

  log_dir: './lightning_logs/baseline/bandgap/schnet'


# default optimizer
optimize:
  type: reduce_on_plateau
  lr: 0.001
  lr_patience: 10
  lr_factor: 0.8
  decay_power: "cosine"
  weight_decay: 0.01
  warmup_steps: 0.02
  max_steps: -1
  optim_type: "adamw"
  end_lr: 1.0e-7
  lr_mult: 1