data:
  root_dir: ./data/benchmark/zeolite
  matid_csv: benchmark
  override: false

  num_grids: [8, 8, 8]
  pes_num_grids: [8, 8, 8]
  repulsion_distance: 0.0

train:
  enable_pes: false
  enable_task: true

  task_name: heat_of_adsorption
  msg_routes: ['p2p']
  readout_node: pn

  max_epochs: 60
  accumulate_grad_batches: 1
  precision: 16-mixed
  batch_size: 16
  model: schnet
  device: [1]
  ckpt_path: ~

  log_dir: ./lightning_logs/multitask/base/zeolite/schnet


# default optimizer
optimize:
  type: default
  lr: 0.001
  decay_power: "cosine"
  weight_decay: 0.01
  warmup_steps: 0.1
  max_steps: -1
  optim_type: "adamw"
  end_lr: 0
  lr_mult: 1