data:
  root_dir: ./data/benchmark/coremof
  matid_csv: benchmark

  grid_size: 30
  patch_size: 3

train:
  task_name: N2-77-100000
  epochs: 100
  batch_size: 16
  log_dir: ./lightning_logs/vit
  log_interval: 10
  devices: [0]

model:
  dim: 512
  depth: 8
  heads: 8
  dropout: 0.1

optimize:
  lr: 0.0001
  decay_power: "cosine"
  weight_decay: 0.01
  warmup_steps: 0.1
  max_steps: -1
  optim_type: "adamw"
  end_lr: 0
  lr_mult: 1